- package-lock.json
- package.json
- src/index.ts
- src/types.ts
Supplies reporter with artifact handler which should work for truffle and non-truffle buidler projects. 
Still having problems integrating the ethers example project with the tests here but believe this should resolve #6...
> Manage artifact consumption in plugin (vs reporter)

- .env
- .gitignore
- test/buidler-ethers-project/test/greeter.ts
- test/mocha.opts
- test/tests.ts
- tsconfig.json
I (mostly) fixed the ethers tests.
There were a few issues:
1. When using `ts` you need to include their type extension's in the `tsconfig.json`. This should be clear in the docs, sorry.
2. `ts-node` normally ignores parts of `tsconfig.json`. To make it work more like `tsc` you have to set the env variable `TS_NODE_FILES` to `true`. I did that with a `.env` file.
3. The Buidler Runtime Environment can/should be imported directly from Buidler project's tests. The `this.env` thing is for testing the plugin itself. It's defined by the `useEnvironment` helper.
4. Mocha was trying to run all the tests, including the Buidler projects' ones. I set it to only run the top-level ones.
Finally, I found an issue with Buidler :( It kills the process after running `TASK_TEST`, so only one of the …
> Fix ethers tests

- package-lock.json
- package.json
- src/index.ts
- test/tests.ts
This PR upgrades Buidler to Beta 9. There are three relevant changes in this new version:
1. There's not a `network` object in the Buidler Runtime Environment, which has the name, config and provider of the currently selected network.
2. `TASK_TEST` doesn't kill the process anymore, so truffle and ethers tests can be run together.
3. `buidler-web3` now uses the stable released of web3.
> Upgrade to Buidler beta 1.0.1

- package.json
- scripts/run-tests.sh
- src/index.ts
- src/provider.ts
- src/types.ts
- test/buidler-truffle-project/buidler.config.js
- test/ethers.ts
- test/helpers.ts
- test/truffle.ts
- yarn.lock
Experimental...super fast but doesn't work correctly for an Ethers-based provider yet (the contract methods are missing).
Truffle-contract / Web3 stuff seems okay though.
(cf: [eth-gas-reporter 171][1])
[1]: https://github.com/cgewecke/eth-gas-reporter/issues/171
> Track gas by wrapping BuidlerEVM provider

- package.json
- src/index.ts
- yarn.lock
We were using a slightly older version older version of Buidler (and possibly Mocha?) 
While testing Synthetix became clear that the way the gas reporter methods used by the wrapped provider were bound to the mocha options object wasn't working. This fix worked...
> Fix way recordTransaction is bound to mocha option object

- src/index.ts
Hey @cgewecke,
I was just helping someone debug a problem with this plugin, and thought that this change would make things easier for most of its users.
TBH, I haven't tested it, and coded it directly here, so the implementation can be wrong 😅 I thought it was good way to showing the idea though.
Best
Pato
> Don't enable the plugin if buidlerevm net is used

- package.json
- scripts/run-tests.sh
- src/index.ts
- src/provider.ts
- src/types.ts
- test/buidler-truffle-project/buidler.config.js
- test/buidlerevm.node.ts
- test/ethers.ts
- test/ganache.node.ts
- test/helpers.ts
- test/truffle.ts
- yarn.lock
(Currently published to npm as buidler-gas-reporter@beta)
+ Only works with buidler-truffle5
+ (Much) faster
+ Does not require an independent node / `localhost`
**Needs**
[1]: https://github.com/nomiclabs/buidler/pull/608
> Support in-process BuidlerEVM

- src/types.ts
The interface `EthGasReporterConfig` is missing `coinmarketcap`.
This PR adds `coinmarketcap?: string;` to `types.ts`
> Add coinmarketcap to types

- src/types.ts
I first set the "buidler" value to the "artifactType" field but I got no gas report. I then looked up [artifactor.js][1] and found out that `artifactType` must be one of:
+ truffle-v5
+ 0xProject-v2
+ buidler-v1
+ ethpm
[1]: https://github.com/cgewecke/eth-gas-reporter/blob/bbf521f137407f106aeec44c730541dda6734ce3/lib/artifactor.js
> perf: strict typing for 'artifactType'

- src/providers.ts
According to the [docs](https://eth.wiki/json-rpc/API#eth_gettransactionreceipt), `eth_getTransactionReceipt` can return `null`, which was causing the provider code to fail.
Originally reported in https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/247.
> Consider possibility of receipt being null

- src/types.ts
When I tried to set up calculating prices in MATIC, I saw that the types for the new fields token and gasPriceApi were not added to the EthGasReporterConfig and I couldn't run tests because of the type warning on 1.0.5 of hardhat-gas-reporter.
> Add types for multi chain gas prices

- src/index.ts
Initial handling for #98... 
(Note: the `--parallel` flag is not actually supported yet. Pending at [hardhat 2359][1])
[1]: https://github.com/nomiclabs/hardhat/pull/2359
> Throw error when --parallel flag is set

- src/index.ts
Per [suggestion][1] in #99. 
[1]: https://github.com/cgewecke/hardhat-gas-reporter/pull/99#issuecomment-1040203097
> Skip gas reporting when --parallel flag detected

- src/index.ts
Hey Chris!
This is a quick PR to optimize this plugin. The change introduced here is that it now imports external libraries right before they are needed. This means that they are not loaded during Hardhat initialization, so that Hardhat loads faster. You can appreciate the difference if you run a `npx hardhat --help` in a project using this version of the plugin and `latest`.
The difference is not huge, but it compounds with other plugins, so I'm doing this for every plugin included in the hardhat toolbox. I'll also send a similar PR to `solidity-coverage`.
~A test is failing, but it was also failing on `master`. I can fix it, but I may require some guidance.~ It passes on the CI
> Import libraries when they are needed

- .gitignore
- package.json
- scripts/run-tests.sh
- src/index.ts
- test/forked.ts
- test/hardhat-forked-project/abi.ts
- test/hardhat-forked-project/contracts/WETH.sol
- test/hardhat-forked-project/hardhat.config.ts
- test/hardhat-forked-project/test/weth.ts
- yarn.lock
Continuation of #153
This has always been broken - I added the option experimentally in #47 but never added a test and just relied on confirmation that it worked in the discussion in #46.  
Also updating hardhat dev dep from 2.11.0 to 2.19.4 here because compiler downloading isn't working in the older version.
> Fixes errors during remote contract gathering (#153)

- .eslintignore
- .gitignore
- package.json
- scripts/run-tests.sh
- src/lib/providers.ts
- src/tasks/gasReporter.ts
- src/types.ts
- test/integration/viem.ts
- test/projects/viem/contracts/Greeter.sol
- test/projects/viem/hardhat.config.ts
- test/projects/viem/test/greeter.ts
- tsconfig.prod.json
- yarn.lock
#170 
Ports #167, #157 to beta.
+ Adds recording for `eth_sendTransaction` if `viem` is exposed on the environment. 
+ if users mix viem with hardhat-ethers, the ethers call counts will be doubled
+ Adds tests for transactions executed with public and wallet clients. 
+ Issues highlighted in #157 about import order and wallet client txs missing are resolved by using `extendProvider` in the beta branch
Closes #167
> Add viem support & tests

- .gitignore
- src/constants.ts
- src/lib/gasData.ts
- src/lib/options.ts
- src/lib/table.ts
- src/types.ts
- src/utils/gas.ts
- test/integration/default.ts
- test/integration/node.ts
- test/integration/options.a.ts
- test/integration/options.b.ts
- test/projects/options/hardhat.options.b.config.ts
#170 
+ Document options in types file
+ Rename `ethPrice` --> `tokenPrice` and add options tests for setting token & gas price defaults
+ Add `outputJSON` option
(CI is failing on forked network tests due to throttling: https://docs.alchemy.com/reference/throughput)
> Add outputJSON option & Rename ethPrice to tokenPrice

- package.json
- scripts/run-tests.sh
- src/lib/render/index.ts
- src/types.ts
- test/integration/options.b.ts
- test/projects/options/hardhat.options.b.config.ts
#170 
Allow user to have different formats for the report they write to file vs. the render on terminal.
> Add `forceTerminalOutputFormat` option

- src/lib/render/terminal.ts
- src/utils/ui.ts
> Make tables thinner with narrower label text

- package.json
- src/lib/collector.ts
- src/lib/resolvers/etherrouter.ts
- src/lib/resolvers/index.ts
- src/lib/resolvers/oz.ts
- src/tasks/gasReporter.ts
- src/types.ts
- test/integration/options.a.ts
- test/integration/oz.ts
- test/projects/options/hardhat.options.a.config.ts
- test/projects/oz/contracts/BeaconBox.sol
- test/projects/oz/contracts/BeaconBoxV2.sol
- test/projects/oz/contracts/ProxyBox.sol
- test/projects/oz/contracts/ProxyBoxV2.sol
- test/projects/oz/test/box.ts
+ Port etherrouter example resolver from eth-gas-reporter
+ Add OZ upgrades resolver
By default, if user does not define their own proxy resolver in the options and `upgrades` or `defender` are defined on the `hre`, the reporter will try to resolve unknown txs by querying OZ for the ERC1967 underlying implementation.
> Add OZ Upgrades system resolver

- src/constants.ts
- src/lib/render/index.ts
- src/tasks/gasReporter.ts
- src/utils/gas.ts
- src/utils/prices.ts
- src/utils/ui.ts
- test/projects/options/hardhat.options.c.config.ts
> Emit warnings when price/gas data remote fetching fails

- src/extend.ts
- src/lib/collector.ts
- src/lib/gasData.ts
- src/lib/options.ts
- src/lib/provider.ts
- src/tasks/builtins.ts
- src/tasks/gasReporter.ts
- src/types.ts
- test/integration/options.default.ts
#170 
+ Imports should be lazy loaded at the entry points if possible to minimize startup times for everything else.
+ Disable or comment out arbitrum stubs 
+ (Deferred via #181 )
+ Comment out TASK_RUN stubs
+ (Deferred via #195 )
> Move imports within task where possible & misc refactoring

- README.md
> Update README for ecotone HF

- src/index.ts
- test/integration/parallel.ts
#218 
This logic used to be inside TASK_TEST, so it needed to `runSuper()`. An error is thrown if there's no override. 
Simply returning could be an issue for anyone who wants to override the reporter tasks. 
Warning is displayed correctly now:
```
>>>>> WARNING (hardhat-gas-reporter plugin) <<<<<<
Gas reporting has been skipped because plugin `hardhat-gas-reporter` does not support the --parallel flag.
>>>>>>>>>>>>>>>>>>>>
```
> Fix crash when --parallel flag is used

- docs/advanced.md
- src/lib/collector.ts
- src/lib/gasData.ts
- src/types.ts
- test/integration/options.default.ts
Adds `intrinsicGas` array to JSON output for each MethodDataItem entry. 
Lets post-processors fine-tune what methods include intrinsic gas in their measurements or isolate the execution gas component for comparative analysis more easily.
> Collect intrinsicGas for JSON output

- src/lib/render/markdown.ts
- src/lib/render/terminal.ts
- src/utils/prices.ts
- src/utils/ui.ts
- test/integration/options.e.ts
- test/integration/options.f.ts
- test/integration/options.g.ts
- test/projects/options/hardhat.options.g.config.ts
Not sure what's going on ... it seems like there aren't reliable blobBaseFee sources. The OP stack GasOracle contracts have reverted to pricing it at 1 wei.
It bounced around btw 20 and 40 gwei all week.
> Fix bug when `blobBaseFee` is sub-gwei

- src/lib/gasData.ts
- test/integration/options.g.ts
Fixes logic bug where a new deployment added between two test runs while tracking is on causes the delta calc fn to exit early. (This is unlikely)
> Fix premature return bug in deployment delta tracking loop

- test/projects/options/test/wallet.ts
- test/unit/gas.ts
Corrected `it("should should allow` to `it("should allow`
Corrected `(bedrock"` to `(bedrock)"`
> fix: typos in unit test descriptions

- package.json
- yarn.lock
Reverts cgewecke/hardhat-gas-reporter#266
There's an issue with how strict treatment of `at` and `layout` keyword treatment is which could affect OZ. 
cf: https://github.com/solidity-parser/parser/issues/123
> Revert "Update solidity-parser/parser to 0.20.0"
